package com.onurkol.app.browser.interfaces;

public interface BrowserActionKeys {
    String ACTION_NAME="BROWSER_ACTION_NAME",
            ACTION_VALUE="BROWSER_ACTION_VALUE";
    // Activity Action Keys
    String KEY_ACTION_TAB_ON_START="BROWSER_OPEN_TAB_WITH_URL",
            KEY_ACTION_INCOGNITO_ON_START="BROWSER_OPEN_INCOGNITO_WITH_URL",
            KEY_ACTION_TAB_ON_CREATE="BROWSER_NEW_TAB_WITH_URL",
            KEY_ACTION_BROWSER_START_INSTALLER="BROWSER_START_INSTALLER";
}
